# Generated by Django 3.2.9 on 2021-12-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_post',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_img/%Y/%m/%d'),
        ),
    ]
